# Generated by Django 4.1 on 2023-07-30 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('coffee', 'Coffee'), ('tea', 'Tea'), ('ade', 'Ade')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('barcode', models.CharField(max_length=20, unique=True)),
                ('expiration_date', models.DateField()),
                ('size', models.CharField(choices=[('small', 'Small'), ('large', 'Large')], max_length=5)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
